"""Initial migration

Revision ID: 60df4eaad28a
Revises: 
Create Date: 2026-01-11 15:36:24.884321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60df4eaad28a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_events',
    sa.Column('raw_event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raw_event_name', sa.String(length=255), nullable=False),
    sa.Column('raw_event_type', sa.String(length=100), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('raw_event_id')
    )
    op.create_index(op.f('ix_raw_events_raw_event_name'), 'raw_events', ['raw_event_name'], unique=False)
    op.create_index(op.f('ix_raw_events_raw_event_type'), 'raw_events', ['raw_event_type'], unique=False)
    op.create_index(op.f('ix_raw_events_user_id'), 'raw_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_events_user_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_raw_event_type'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_raw_event_name'), table_name='raw_events')
    op.drop_table('raw_events')
    # ### end Alembic commands ###
