{
 "title": "Logs Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "pixel_track",
     "rawSql": "SELECT\r\n  $__timeGroup(timestamp, '1m') AS time,\r\n  count(*) AS value\r\nFROM raw_events\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Time taken",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "pixel_track",
     "rawSql": "SELECT\r\n  $__timeGroup(timestamp, '1m') AS time,\r\n  AVG((payload->>'duration_ms')::int) AS value\r\nFROM raw_events\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND raw_event_type = 'http'\r\n  AND payload->>'duration_ms' IS NOT NULL\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "HTTP: Route Performance",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "pixel_track",
     "rawSql": "SELECT\r\n  payload->>'path' AS \"Route\",                 \r\n  COUNT(*) AS \"Requests Count\",                \r\n  AVG((payload->>'duration_ms')::int)::int AS \"Avg Time (ms)\",\r\n  MAX((payload->>'duration_ms')::int) AS \"Max Time (ms)\"\r\nFROM raw_events\r\nWHERE\r\n  $__timeFilter(timestamp)                     \r\n  AND raw_event_type = 'http'                  \r\n  AND payload->>'path' IS NOT NULL             \r\nGROUP BY 1\r\nORDER BY 3 DESC                                \r\nLIMIT 20                                      "
    }
   ]
  }
 ]
}